#!/bin/bash

set -e

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly BASH_COMMONS_DIR="$SCRIPT_DIR/../bash-commons"

source "$BASH_COMMONS_DIR/logging.sh"
source "$BASH_COMMONS_DIR/assertions.sh"
source "$BASH_COMMONS_DIR/strings.sh"
source "$BASH_COMMONS_DIR/os.sh"

readonly DEFAULT_COUCHBASE_VERSION="5.1.0"
readonly DEFAULT_COUCHBASE_SHA256_CHECKSUM_UBUNTU_16_04="4d6a1f159577f283f6f980f6ab9161630eb2d8fd228429029de004b1be46ad76"
readonly DEFAULT_COUCHBASE_SHA256_CHECKSUM_AMAZON_LINUX="6c87268118cd21a0083a99aee8164712b3536720c11e8fcd7fe55646c8c83c56"
readonly DEFAULT_SWAPINESS="0"

readonly SWAPINESS_CONFIG_FILE="/etc/sysctl.conf"
readonly DISABLE_THP_BOOT_SCRIPT="/etc/init.d/disable-thp"

readonly DEFAULT_COUCHBASE_DIR="/opt/couchbase"
readonly DEFAULT_COUCHBASE_BIN_DIR="$DEFAULT_COUCHBASE_DIR/bin"
readonly BASH_COMMONS_INSTALL_DIR="$DEFAULT_COUCHBASE_DIR/bash-commons"

function print_usage {
  echo
  echo "Usage: install-couchbase-server [options]"
  echo
  echo "This script can be used to install Couchbase Server and its dependencies. This script has been tested with Ubuntu 16.04 and Amazon Linux 2."
  echo
  echo "Options:"
  echo
  echo -e "  --version\t\tThe version of Couchbase to install. Default: $DEFAULT_COUCHBASE_VERSION."
  echo -e "  --checksum\t\tThe SHA-256 checksum of the Couchbase package. Required if --version is specified. You can get it from the downloads page of the Couchbase website."
  echo -e "  --swapiness\t\tThe OS swapiness setting to use. Couchbase recommends setting this to 0. Default: $DEFAULT_SWAPINESS."
  echo
  echo "Example:"
  echo
  echo "  install-couchbase-server --version $DEFAULT_COUCHBASE_VERSION --checksum $DEFAULT_COUCHBASE_SHA256_CHECKSUM_UBUNTU_16_04"
}

function install_couchbase_on_ubuntu {
  local readonly version="$1"
  local readonly checksum="$2"

  log_info "Installing Couchbase on Ubuntu"

  # TODO: what about the community edition?
  local readonly filepath="couchbase-server-enterprise_${version}-ubuntu16.04_amd64.deb"
  local readonly url="https://packages.couchbase.com/releases/$version/$filepath"

  log_info "Installing Couchbase dependencies"
  sudo DEBIAN_FRONTEND=noninteractive apt-get update
  sudo apt-get install -y python-httplib2 openssl

  log_info "Downloading Couchbase from $url to $filepath"
  curl --location --silent --fail --show-error -O "$url"

  log_info "Verifying checksum is $checksum"
  echo "$checksum $filepath" | sha256sum -c

  # Install Couchbase, but configure it to NOT start on boot. This allows the run-couchbase-server script to configure
  # Couchbase, including what ports to use, and THEN boot it up.
  log_info "Installing Couchbase from $filepath"
  sudo INSTALL_DONT_START_SERVER=1 dpkg -i "$filepath"
  sudo systemctl disable couchbase-server

  log_info "Cleaning up $filepath"
  rm -f "$filepath"
}

function install_couchbase_on_amazon_linux {
  local readonly version="$1"
  local readonly checksum="$2"

  log_info "Installing Couchbase on Amazon Linux"

  # TODO: what about the community edition?
  local readonly filepath="couchbase-server-enterprise-${version}-centos6.x86_64.rpm"
  local readonly url="https://packages.couchbase.com/releases/$version/$filepath"

  log_info "Installing Couchbase dependencies"
  sudo yum update -y
  sudo yum install -y openssl

  log_info "Downloading Couchbase from $url to $filepath"
  curl --location --silent --fail --show-error -O "$url"

  log_info "Verifying checksum is $checksum"
  echo "$checksum $filepath" | sha256sum -c

  # Install Couchbase, but configure it to NOT start on boot. This allows the run-couchbase-server script to configure
  # Couchbase, including what ports to use, and THEN boot it up.
  log_info "Installing Couchbase from $filepath"
  sudo INSTALL_DONT_START_SERVER=1 rpm --install "$filepath"
  sudo chkconfig couchbase-server off

  log_info "Cleaning up $filepath"
  rm -f "$filepath"
}

# Disabling transparent huge pages is recommended for Couchbase servers.
# https://developer.couchbase.com/documentation/server/current/install/thp-disable.html
function disable_transparent_huge_pages {
  log_info "Adding boot script $DISABLE_THP_BOOT_SCRIPT to disable transparent huge pages"
  sudo cp "$SCRIPT_DIR/disable-thp" "$DISABLE_THP_BOOT_SCRIPT"
}

# A swapiness of 0 or 1 is recommended for Couchbase servers.
# https://developer.couchbase.com/documentation/server/current/install/install-swap-space.html
function update_swapiness {
  local readonly swapiness="$1"

  log_info "Updating OS swapiness settings to $swapiness in $SWAPINESS_CONFIG_FILE"

  replace_or_append_in_file "^vm.swappiness.*=.*$" "vm.swapiness = $swapiness" "$SWAPINESS_CONFIG_FILE"
}

function install_couchbase_scripts {
  local readonly dest_dir="$1"

  local readonly run_couchbase_src="$SCRIPT_DIR/../run-couchbase-server/run-couchbase-server"
  local readonly run_couchbase_dest="$dest_dir/run-couchbase-server"
  log_info "Copying $run_couchbase_src to $run_couchbase_dest"
  sudo cp "$run_couchbase_src" "$run_couchbase_dest"
  sudo chmod +x "$run_couchbase_dest"

  local readonly run_replication_src="$SCRIPT_DIR/../run-replication/run-replication"
  local readonly run_replication_dest="$dest_dir/run-replication"
  log_info "Copying $run_replication_src to $run_replication_dest"
  sudo cp "$run_replication_src" "$run_replication_dest"
  sudo chmod +x "$run_replication_dest"
}

function install_bash_commons {
  local readonly dest_dir="$1"
  local readonly src_dir="$BASH_COMMONS_DIR"

  log_info "Copying $src_dir to $dest_dir"
  sudo cp -r "$src_dir" "$dest_dir"
}

function install {
  local version="$DEFAULT_COUCHBASE_VERSION"
  local checksum=$(is_amazon_linux && echo -n "$DEFAULT_COUCHBASE_SHA256_CHECKSUM_AMAZON_LINUX" || echo -n "$DEFAULT_COUCHBASE_SHA256_CHECKSUM_UBUNTU_16_04")
  local swapiness="$DEFAULT_SWAPINESS"

  while [[ $# > 0 ]]; do
    local key="$1"

    case "$key" in
      --version)
        assert_not_empty "$key" "$2"
        version="$2"
        shift
        ;;
      --checksum)
        assert_not_empty "$key" "$2"
        checksum="$2"
        shift
        ;;
      --swapiness)
        assert_not_empty "$key" "$2"
        swapiness="$2"
        shift
        ;;
      --help)
        print_usage
        exit
        ;;
      *)
        log_error "Unrecognized argument: $key"
        print_usage
        exit 1
        ;;
    esac

    shift
  done

  assert_is_installed "curl"

  if [[ ! -z "$version" && -z "$checksum" ]]; then
    log_error "You must specify the --checksum parameter when specifying the --version parameter. You can find the checksums on the Couchbase downloads page."
    exit 1
  fi

  log_info "Starting Couchbase install..."

  if is_ubuntu "16.04"; then
    install_couchbase_on_ubuntu "$version" "$checksum"
  elif is_amazon_linux "2"; then
    install_couchbase_on_amazon_linux "$version" "$checksum"
  else
    log_error "This script only supports Ubuntu 16.04 and Amazon Linux 2."
    exit 1
  fi

  update_swapiness "$swapiness"
  disable_transparent_huge_pages
  install_couchbase_scripts "$DEFAULT_COUCHBASE_BIN_DIR"
  install_bash_commons "$BASH_COMMONS_INSTALL_DIR"

  log_info "Couchbase installed successfully!"
}

install "$@"

