#!/bin/bash
# This is a mock version of a script with the same name that replaces all the real methods, which rely on external
# dependencies, such EC2 Metadata and AWS API calls, with mock versions that can run entirely locally. This allows us
# to test all the scripts completely locally using Docker.

set -e

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/logging.sh"
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/assertions.sh"

function run {
  local mount_point
  local owner

  while [[ $# > 0 ]]; do
    local key="$1"

    case "$key" in
      --mount-point)
        mount_point="$2"
        shift
        ;;
      --owner)
        owner="$2"
        shift
        ;;
    esac

    shift
  done

  assert_not_empty "--mount-point" "$mount_point"
  assert_not_empty "--owner" "$owner"

  log_info "Running MOCK version of mount-ebs-volume. Instead of mount a real volume, will simply create a folder at $mount_point owned by $owner."
  sudo mkdir -p "$mount_point"
  sudo chown -R "$owner:$owner" "$mount_point"
}

run "$@"